/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MemoryDemo */

#ifndef _Included_MemoryDemo
#define _Included_MemoryDemo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
